In [1]:
import gym
from stable_baselines3 import DQN,A2C
import adaptive_tutor
import numpy as np

In [2]:
env = gym.make('adaptive_tutor/PuzzleTutorEnv-v0', render_mode=None) 

../maia_weights/maia_1100.pb
1


In [9]:
# Define a wrapper class for observation preprocessing
class CustomPreprocessingWrapper(gym.ObservationWrapper):
    def __init__(self, env):
        super().__init__(env)
        self.observation_space = gym.spaces.Box(low=0, high=1, shape=(10,), dtype=np.int32)

    def observation(self, observation):
        return observation['themes_covered']

In [10]:
env = CustomPreprocessingWrapper(env)
env.reset()

../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 7


(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 {'info': {'gt_1900': 0,
   '1400-1500': 0,
   '1200-1300': 0,
   '1000-1100': 0,
   '1500-1600': 0,
   '1800-1900': 0,
   '1100-1200': 0,
   '1700-1800': 0,
   'lt_900': 0,
   '1600-1700': 0,
   '900-1000': 0,
   '1300-1400': 0}})

In [5]:
model = DQN("MlpPolicy", env, verbose=1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


/Users/shikharrastogi/opt/anaconda3/envs/stable_b/lib/python3.9/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


In [11]:
# model.learn(total_timesteps=100000, progress_bar=True)
# model.save("dqn_sb")

In [20]:
model = A2C.load("adaptive_tutor/logs/a2c_model_10000_steps")
# model.load_replay_buffer('logs/rl_model_replay_buffer_10000_steps.pkl')
model.set_env(env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


/Users/shikharrastogi/opt/anaconda3/envs/stable_b/lib/python3.9/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


In [1]:
action_space = list(np.load('adaptive_tutor/action_space.npy', allow_pickle=True))

NameError: name 'np' is not defined

In [22]:
pred, out = model.predict([0,0,0,0,0,0,0,0,0,0])
action_space[pred]

('1400-1500', 'special_moves')

In [23]:
obs, info = env.reset()
i=0
while i<1:
    print(obs)
    action, _states = model.predict(obs, deterministic=False)
    print(action_space[action])
    obs, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        obs, info = env.reset()
        i+=1

../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 7
[0 0 0 0 0 0 0 0 0 0]
('1200-1300', 'piece_specific_endgames')


<UciProtocol (pid=42231)>: stderr >>        _
<UciProtocol (pid=42231)>: stderr >> |   _ | |
<UciProtocol (pid=42231)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=42231)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=42231)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=42231)>: stderr >> Initialized metal backend on device Apple M1


[   0    0    0    0    0    0 1276    0    0    0]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0    0 1208]
('1200-1300', 'defensive_tactics')
[   0    0    0    0    0    0 1276    0   

KeyboardInterrupt: 

In [3]:
import random
action_space = list(np.load('adaptive_tutor/action_space_small.npy', allow_pickle=True))

In [4]:
random.choice(action_space)

('1100-1200', 'checkmate_patterns')

In [5]:
# Random Action Selection Baseline

In [6]:
num_steps_arr = []
obs, info = env.reset()
i=0
for i in range(10):
    num_steps = 0
    while True:
        action = random.choice(action_space)
        obs, reward, terminated, truncated, info = env.step(action_space.index(action))
        num_steps+=1
        if terminated or truncated:
            obs, info = env.reset()
            num_steps_arr.append(num_steps)
            break


<UciProtocol (pid=47140)>: stderr >>        _
<UciProtocol (pid=47140)>: stderr >> |   _ | |
<UciProtocol (pid=47140)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47140)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47140)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47140)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3


/Users/shikharrastogi/opt/anaconda3/envs/stable_b/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


../maia_weights/maia_1300.pb
2
Bot_Upgraded


<UciProtocol (pid=47142)>: stderr >>        _
<UciProtocol (pid=47142)>: stderr >> |   _ | |
<UciProtocol (pid=47142)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47142)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47142)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47142)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1500.pb


<UciProtocol (pid=47148)>: stderr >>        _
<UciProtocol (pid=47148)>: stderr >> |   _ | |
<UciProtocol (pid=47148)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47148)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47148)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47148)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb


<UciProtocol (pid=47151)>: stderr >>        _
<UciProtocol (pid=47151)>: stderr >> |   _ | |
<UciProtocol (pid=47151)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47151)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47151)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47151)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 30
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb


<UciProtocol (pid=47153)>: stderr >>        _
<UciProtocol (pid=47153)>: stderr >> |   _ | |
<UciProtocol (pid=47153)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47153)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47153)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47153)>: stderr >> Initialized metal backend on device Apple M1


2
Bot_Upgraded
../maia_weights/maia_1500.pb


<UciProtocol (pid=47156)>: stderr >>        _
<UciProtocol (pid=47156)>: stderr >> |   _ | |
<UciProtocol (pid=47156)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47156)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47156)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47156)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb


<UciProtocol (pid=47157)>: stderr >>        _
<UciProtocol (pid=47157)>: stderr >> |   _ | |
<UciProtocol (pid=47157)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47157)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47157)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47157)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 35
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb


<UciProtocol (pid=47161)>: stderr >>        _
<UciProtocol (pid=47161)>: stderr >> |   _ | |
<UciProtocol (pid=47161)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47161)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47161)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47161)>: stderr >> Initialized metal backend on device Apple M1


2
Bot_Upgraded
../maia_weights/maia_1500.pb


<UciProtocol (pid=47166)>: stderr >>        _
<UciProtocol (pid=47166)>: stderr >> |   _ | |
<UciProtocol (pid=47166)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47166)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47166)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47166)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb


<UciProtocol (pid=47169)>: stderr >>        _
<UciProtocol (pid=47169)>: stderr >> |   _ | |
<UciProtocol (pid=47169)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47169)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47169)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47169)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 40
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb
2
Bot_Upgraded


<UciProtocol (pid=47172)>: stderr >>        _
<UciProtocol (pid=47172)>: stderr >> |   _ | |
<UciProtocol (pid=47172)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47172)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47172)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47172)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1500.pb
3
Bot_Upgraded


<UciProtocol (pid=47174)>: stderr >>        _
<UciProtocol (pid=47174)>: stderr >> |   _ | |
<UciProtocol (pid=47174)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47174)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47174)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47174)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1700.pb


<UciProtocol (pid=47180)>: stderr >>        _
<UciProtocol (pid=47180)>: stderr >> |   _ | |
<UciProtocol (pid=47180)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47180)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47180)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47180)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 50
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb


<UciProtocol (pid=47182)>: stderr >>        _
<UciProtocol (pid=47182)>: stderr >> |   _ | |
<UciProtocol (pid=47182)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47182)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47182)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47182)>: stderr >> Initialized metal backend on device Apple M1


2
Bot_Upgraded
../maia_weights/maia_1500.pb


<UciProtocol (pid=47187)>: stderr >>        _
<UciProtocol (pid=47187)>: stderr >> |   _ | |
<UciProtocol (pid=47187)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47187)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47187)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47187)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb


<UciProtocol (pid=47190)>: stderr >>        _
<UciProtocol (pid=47190)>: stderr >> |   _ | |
<UciProtocol (pid=47190)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47190)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47190)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47190)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 49
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb
2
Bot_Upgraded


<UciProtocol (pid=47194)>: stderr >>        _
<UciProtocol (pid=47194)>: stderr >> |   _ | |
<UciProtocol (pid=47194)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47194)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47194)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47194)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1500.pb


<UciProtocol (pid=47197)>: stderr >>        _
<UciProtocol (pid=47197)>: stderr >> |   _ | |
<UciProtocol (pid=47197)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47197)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47197)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47197)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb
4
Bot_Upgraded
Number of steps 32
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3


<UciProtocol (pid=47199)>: stderr >>        _
<UciProtocol (pid=47199)>: stderr >> |   _ | |
<UciProtocol (pid=47199)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47199)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47199)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47199)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1300.pb


<UciProtocol (pid=47204)>: stderr >>        _
<UciProtocol (pid=47204)>: stderr >> |   _ | |
<UciProtocol (pid=47204)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47204)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47204)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47204)>: stderr >> Initialized metal backend on device Apple M1


2
Bot_Upgraded
../maia_weights/maia_1500.pb
3
Bot_Upgraded


<UciProtocol (pid=47205)>: stderr >>        _
<UciProtocol (pid=47205)>: stderr >> |   _ | |
<UciProtocol (pid=47205)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47205)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47205)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47205)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1700.pb


<UciProtocol (pid=47208)>: stderr >>        _
<UciProtocol (pid=47208)>: stderr >> |   _ | |
<UciProtocol (pid=47208)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47208)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47208)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47208)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 45
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb
2
Bot_Upgraded


<UciProtocol (pid=47217)>: stderr >>        _
<UciProtocol (pid=47217)>: stderr >> |   _ | |
<UciProtocol (pid=47217)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47217)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47217)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47217)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1500.pb


<UciProtocol (pid=47218)>: stderr >>        _
<UciProtocol (pid=47218)>: stderr >> |   _ | |
<UciProtocol (pid=47218)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47218)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47218)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47218)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb
4
Bot_Upgraded
Number of steps 58
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3


<UciProtocol (pid=47221)>: stderr >>        _
<UciProtocol (pid=47221)>: stderr >> |   _ | |
<UciProtocol (pid=47221)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47221)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47221)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47221)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1300.pb


<UciProtocol (pid=47228)>: stderr >>        _
<UciProtocol (pid=47228)>: stderr >> |   _ | |
<UciProtocol (pid=47228)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47228)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47228)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47228)>: stderr >> Initialized metal backend on device Apple M1


2
Bot_Upgraded
../maia_weights/maia_1500.pb


<UciProtocol (pid=47230)>: stderr >>        _
<UciProtocol (pid=47230)>: stderr >> |   _ | |
<UciProtocol (pid=47230)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47230)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47230)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47230)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb


<UciProtocol (pid=47235)>: stderr >>        _
<UciProtocol (pid=47235)>: stderr >> |   _ | |
<UciProtocol (pid=47235)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47235)>: stderr >> Loading weights file from: ../maia_weights/maia_1100.pb
<UciProtocol (pid=47235)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47235)>: stderr >> Initialized metal backend on device Apple M1


4
Bot_Upgraded
Number of steps 61
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3
../maia_weights/maia_1300.pb
2
Bot_Upgraded


<UciProtocol (pid=47240)>: stderr >>        _
<UciProtocol (pid=47240)>: stderr >> |   _ | |
<UciProtocol (pid=47240)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47240)>: stderr >> Loading weights file from: ../maia_weights/maia_1300.pb
<UciProtocol (pid=47240)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47240)>: stderr >> Initialized metal backend on device Apple M1


../maia_weights/maia_1500.pb


<UciProtocol (pid=47243)>: stderr >>        _
<UciProtocol (pid=47243)>: stderr >> |   _ | |
<UciProtocol (pid=47243)>: stderr >> |_ |_ |_| v0.30.0+git.dirty built Jul 22 2023
<UciProtocol (pid=47243)>: stderr >> Loading weights file from: ../maia_weights/maia_1500.pb
<UciProtocol (pid=47243)>: stderr >> Creating backend [metal]...
<UciProtocol (pid=47243)>: stderr >> Initialized metal backend on device Apple M1


3
Bot_Upgraded
../maia_weights/maia_1700.pb
4
Bot_Upgraded
Number of steps 40
../maia_weights/maia_1100.pb
1
Starting episode with x,y = 100 3


In [7]:
sum(num_steps_arr)/len(num_steps_arr)

44.0

In [8]:
np.mean(num_steps_arr)

44.0

In [9]:
np.std(np.array(num_steps_arr))

10.0

In [19]:
num_steps_arr

[13,
 4,
 4,
 41,
 4,
 41,
 36,
 17,
 32,
 20,
 42,
 20,
 5,
 11,
 47,
 7,
 5,
 4,
 13,
 35,
 16,
 38,
 25,
 11,
 32,
 5,
 20,
 16,
 47,
 10,
 12,
 32,
 46,
 4,
 12,
 6,
 36,
 34,
 9,
 4,
 48,
 37,
 5,
 49,
 21,
 12,
 42,
 8,
 8,
 35,
 36,
 38,
 27,
 20,
 10,
 18,
 7,
 7,
 7,
 35,
 9,
 18,
 48,
 31,
 45,
 27,
 41,
 20,
 37,
 17,
 5,
 14,
 29,
 5,
 7,
 9,
 8,
 20,
 8,
 40,
 4,
 6,
 11,
 16,
 33,
 30,
 4,
 4,
 33,
 6,
 12,
 35,
 15,
 43,
 36,
 12,
 48,
 30,
 45,
 36]